### ISSUE TITLE
no matches for kind "BackupStorageLocation" and "VolumeSnapshotLocation"

### ISSUE THREAD

**Issue by adamyang** [AliyunContainerService/velero-plugin#1]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
run kubectl apply -f install/velero.yaml
output message end with:
unable to recognize "velero.yaml": no matches for kind "BackupStorageLocation" in version "velero.io/v1"
unable to recognize "velero.yaml": no matches for kind "VolumeSnapshotLocation" in version "velero.io/v1"

**What did you expect to happen:**
apply success without errors

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
aliyun linux
- Velero version: (use `ark version`):v1.0.0
- Kubernetes version: (use `kubectl version`):v1.15.0
- Kubernetes installer & version: aliyun
- Cloud provider or hardware configuration: aliyun
- OS (e.g. from `/etc/os-release`): aliyun

**Comment by haoshuwei** [comment]
@adamyang Velero crds and other kubernetes resources are all in one yaml file [install/velero](https://github.com/AliyunContainerService/velero-plugin/blob/master/install/velero.yaml),  when deployment is deployed but crds are not ready, it will display error message like this.    You can retry `kubectl apply -f install/velero.yaml`  to make it work. 

In addition, I will split velero.yaml to two files to avoid this occur agin
