### ISSUE TITLE
velero 部署时区为UTC时区，可否提供配置将时区设置为Asia/Shanghai

### ISSUE THREAD

**Issue by sunny0826** [AliyunContainerService/velero-plugin#12]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
在做定时备份的时候，发现时区为UTC时区，希望试用Asia/Shanghai

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version: (use `ark version`):
Client:
        Version: v1.1.0
        Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
        Version: v1.1.0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-aliyun.1", GitCommit:"a4182a8", GitTreeState:"", BuildDate:"2019-08-27T06:03:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by sunny0826** [comment]
由于时区问题，导致`velero schedule create <SCHEDULE NAME> --schedule "0 7 * * *`命令进行定时备份时，需要采用UTC时区时间进行定时

**Comment by haoshuwei** [comment]
I have created a issue in velero project, we can watch [https://github.com/vmware-tanzu/velero/issues/2061](https://github.com/vmware-tanzu/velero/issues/2061) to see how is the velero community thinking about this.

**Comment by prometheus-tao** [comment]
@sunny0826 velero deployment yaml add env TZ=Asia/Shanghai
