### ISSUE TITLE
 Backup store contains invalid top-level directories: [velero]

### ISSUE THREAD

**Issue by cycwll** [AliyunContainerService/velero-plugin#46]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

An error occurred after installed:

time="2022-02-23T13:54:10Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:430"
time="2022-02-23T13:54:10Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: Backup store contains invalid top-level directories: [velero]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Install command:

BUCKET=velero-aks
REGION=cn-beijing

velero install \
  --provider alibabacloud \
  --image registry.$REGION.aliyuncs.com/acs/velero:1.4.2-2b9dce65-aliyun \
  --bucket $BUCKET \
  --secret-file ./credentials-velero \
  --use-volume-snapshots=false \
  --backup-location-config region=$REGION \
  --use-restic \
  --plugins registry.$REGION.aliyuncs.com/acs/velero-plugin-alibabacloud:v1.0.0-2d33b89 \
  --wait

**Comment by yang0009** [comment]
你好,请问解决了吗,我也遇到同样的问题

**Comment by yang0009** [comment]
目前我新建了bucket 不会报这个错,已经成功了,程序会在根目录下创建一个buckups目录,可能bucket需要一个干净的,你可以尝试一下

**Comment by cycwll** [comment]
> 目前我新建了bucket 不会报这个错,已经成功了,程序会在根目录下创建一个buckups目录,可能bucket需要一个干净的,你可以尝试一下

是的，同样的办法解决了。
