### ISSUE TITLE
Error attempting to get volume ID for persistent volume

### ISSUE THREAD

**Issue by chenzhenyang** [AliyunContainerService/velero-plugin#7]
time="2019-08-23T00:52:24Z" level=error msg="Error attempting to get volume ID for persistent volume" backup=velero/nginx-backup-volume3 error="rpc error: code = Unknown desc = spec.FlexVolume.Options['VolumeId'] not found" error.file="/Users/hao/go/src/github.com/AliyunContainerService/velero-plugin/pkg/alibabacloud/volume_snapshotter.go:300" error.function=github.com/AliyunContainerService/velero-plugin/pkg/alibabacloud.getEBSDiskID group=v1 logSource="pkg/backup/item_backupper.go:415" name=d-8vb87uf50ubbq62ugrjo namespace=nginx-example persistentVolume=d-8vb87uf50ubbq62ugrjo resource=pods volumeSnapshotLocation=default

在国内阿里云上，使用阿里云的容器服务，运行with-pvc.yaml，查看日志，报如上错误。

**Comment by haoshuwei** [comment]
@chenzhenyang This is caused by the pv's yaml description which uses spec.FlexVolume.Options['volumeId'] but velero need spec.FlexVolume.Options['VolumeId'].  I have updated the examples to uses pvc  to create pv dynamically, please have a try again.
